name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: List files
        run: |
          pwd
          ls   
          
      - name: Checkout
        uses: actions/checkout@v5

      - name: List files after checkout
        run: |
          pwd
          ls   

      - name: simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Mikheil
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.Time}}"


