name: Matrix
on: [push]
jobs:
  node_version:
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node -v
    #   - uses: actions/setup-node@v1
    #     with:
    #       node-version: 24
    #   - name: Lonode version
    #     run: node -v
